# Generated by Django 5.2 on 2025-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='netflixData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
                ('title', models.CharField()),
                ('director', models.CharField()),
                ('cast', models.CharField()),
                ('country', models.CharField()),
                ('date_added', models.CharField()),
                ('release_year', models.DateField()),
                ('rating', models.CharField()),
                ('duration', models.CharField()),
                ('listed_in', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
    ]
